name: Generate SBOM

on:
  push:
    branches: [ main ]
  workflow_dispatch:       # lets you run it manually in the UI

permissions:
  contents: write          # so the upload-artifact step can run

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create SBOM (CycloneDX)
        uses: CycloneDX/gh-cyclonedx-action@v2
        with:
          output: "bom.xml"

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: bom.xml
